name: GitHub Apps Automation

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/**/*.json'

permissions:
  contents: read

jobs:
  create-app:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
