name: Sync Manifests to Index
on:
  push:
    branches:
      - main
    paths:
      - 'manifests/*.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_APP_ID }}
          private-key: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main

      - name: Generate manifests.json
        run: ./scripts/manifest-sync.sh

      - name: Configure Git
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add docs/manifests.json
          git diff --staged --quiet || git commit -m "chore: auto-update manifests.json on push to main"
          git push
