name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # Needed to read the repository contents
  pull-requests: write # Needed to write to PR
  actions: read # To read workflow information

jobs:
  pre-commit-check:
    name: Check Pre-Commit Install File
    runs-on: ubuntu-latest
    steps:
      - uses: dteenergy/cloud-platform-github-actions/pre-commit-check-install@main

  assign-author:
    name: Assign Pull Request to Author
    runs-on: ubuntu-latest
    steps:
      - uses: dteenergy/cloud-platform-github-actions/pull-request/assign-author@main
