name: Push Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of dispatch'
        required: false
        default: 'Manual dispatch'
concurrency:
  group: ${{ github.ref == 'refs/heads/main' }}
  cancel-in-progress: false

permissions:
  contents: write # Needed to push changes back to the repo
  actions: read # To read workflow information

jobs:
  pre-commit-replace:
    name: Replace Pre-Commit Install File
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Commit Replace Install
        uses: dteenergy/cloud-platform-github-actions/pre-commit-replace-install@main
        with:
          app-id: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_APP_ID }}
          private-key: ${{ secrets.CLOUD_PLATFORM_GITHUB_ACTION_PRIVATE_KEY }}
